### ISSUE TITLE
Your Windows Application Management documentation links to removed files

### ISSUE THREAD

**Issue by troykelly** [TheJumpCloud/support#543]
**Describe the bug**
Your documentation here: https://jumpcloud.com/resources/install-manage-applications-remote-systems
Refers to here: `Import-JCCommand -URL ‘https://git.io/Je0G5’`
Which, doesn't exist.

**To Reproduce**
1. Try to set up another windows workstation
2. Notice that none of the applications install
3. Get annoyed there is no "retry" or "trigger" on the installation
4. Try reading the documentation
5. Notice it's pretty poor
6. Copy the instructions
7. FAIL

**Expected behavior**
I'd expect JumpCloud to have a working application management layer.
I'd expect documetnation to be accurate.

**Links**
Links to file or script with regards to the issue.
An old version is here: https://github.com/TheJumpCloud/support/blob/MDM-command/PowerShell/JumpCloud%20Commands%20Gallery/Windows%20Commands/Chocolatey/Windows%20-%20Install%20Chocolatey.md

**Screenshots**
N/A

****System Device (please complete the following information):****
N/A

**Additional context**
For feature requests, go to: https://support.jumpcloud.com/support/s/article/to-submit-a-jumpcloud-feature-request2

**Comment by jworkmanjc** [comment]
Hello @troykelly, I agree with you the quality of documentation for this suggested way of managing chocolatey applications is poor. I requested that our website take the article down. 

This article was written before JumpCloud rolled out it's [software management](https://jumpcloud.com/support/software-management) capability which does leverage chocolatey.

For what it's worth, you can see that script that we used to recommend to customers to install Chocolatey. There's two ways to manage applications in JumpCloud. 
1. You can install Chocolatey as a standalone application on all your devices and run individual commands to install your desired applications
2. You can leverage the software management feature within Windows to manage choco applications (and or point towards a private choco repository) https://jumpcloud.com/support/software-management-windows

Regarding option 1. I was able to successfully install choco just using the instructions from https://docs.chocolatey.org/en-us/choco/setup. Steps below:

1. Create a command in JumpCloud, set type to windows and select "Windows PowerShell" 
2. Paste the command body contents: `Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))`
3. Assign the command to a device and click run.

I was able to install a software package after this step. Initially, I attempted to install [7zip](https://community.chocolatey.org/packages/7zip), but the command failed due to the license agreement which must be accepted. Changing my command `choco install 7zip` to `choco install 7zip -y` installed the desired application and remotely accepted the license agreement. Certain applications are going to have licenses which must be accepted in which case, the [choco documentation](https://docs.chocolatey.org/en-us/choco/commands/install) should be referenced.

You are correct in thinking the documentation on our blog was lacking, I've set that to be removed. The best documentation for installing software or using a package library should come from the software vendor itself. I hope that the example I provided above should suffice in your testing with chocolatey and JumpCloud commands and I apologize that the lack of documentation in the first place left you without answers.
