### ISSUE TITLE
JumpCloud RADIUS - User Certificates on Windows Not Trusted

### ISSUE THREAD

**Issue by sonny-mei** [TheJumpCloud/support#604]
I am experiencing an issue where user certificates on Windows are not being recognized as trusted. This issue is causing disruptions as these certificates are essential for secure connections and authentication processes within our environment.

One potential resolution could be to import the CA certificate into the trusted root certificate authorities store on the affected Windows machines. However, I am unsure of the correct procedure or if there are other best practices for ensuring these certificates are trusted system-wide.

Any insights or recommendations on how to address this issue would be greatly appreciated.

Thank you,
Sonny Mei

![image](https://github.com/user-attachments/assets/f87dff50-f925-4c30-8ccd-197e88f7ef21)

**Comment by jworkmanjc** [comment]
@sonny-mei, I commented on another issue you posted. I'm not positive that windows will actually need to trust the cert distributed to devices since it's only used for Radius authentication, the chain of trust is validated on JumpCloud when the certificate is compared against the CA cert in your Radius configuration. I'm happy to chat in further detail however, it's likely worth both our times to meet and compare your goals vs. what's exactly possible at the moment. If you'd like feel free to send me an email joe.workman@jumpcloud.com and we can schedule a call.
